version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bamboo_smtp
    versions:
    - 3.1.3
    - 4.0.1
  - dependency-name: junit_formatter
    versions:
    - 3.2.0
  - dependency-name: absinthe_plug
    versions:
    - 1.5.5
    - 1.5.7
    - 1.5.8
  - dependency-name: absinthe
    versions:
    - 1.6.1
    - 1.6.2
    - 1.6.3
    - 1.6.4
  - dependency-name: phoenix_live_reload
    versions:
    - 1.3.1
  - dependency-name: geo
    versions:
    - 3.3.8
    - 3.4.2
  - dependency-name: geo_postgis
    versions:
    - 3.4.0
  - dependency-name: ex_cldr
    versions:
    - 2.19.0
    - 2.19.1
    - 2.20.0
  - dependency-name: tesla
    versions:
    - 1.4.1
  - dependency-name: ex_doc
    versions:
    - 0.24.0
    - 0.24.1
    - 0.24.2
  - dependency-name: ueberauth_discord
    versions:
    - 0.6.0
  - dependency-name: timex
    versions:
    - 3.6.4
    - 3.7.1
    - 3.7.3
    - 3.7.5
  - dependency-name: oban
    versions:
    - 2.4.2
    - 2.4.3
    - 2.5.0
    - 2.6.1
  - dependency-name: floki
    versions:
    - 0.30.0
    - 0.30.1
  - dependency-name: bamboo
    versions:
    - 1.7.0
    - 1.7.1
    - 2.0.2
  - dependency-name: sobelow
    versions:
    - 0.11.1
  - dependency-name: ex_machina
    versions:
    - 2.7.0
  - dependency-name: linkify
    versions:
    - 0.5.0
  - dependency-name: dialyxir
    versions:
    - 1.1.0
  - dependency-name: phoenix
    versions:
    - 1.5.8
  - dependency-name: ex_unit_notifier
    versions:
    - 1.1.0
  - dependency-name: credo
    versions:
    - 1.5.5
  - dependency-name: cors_plug
    versions:
    - 2.0.3
  - dependency-name: sentry
    versions:
    - 8.0.4
  - dependency-name: exvcr
    versions:
    - 0.12.2
- package-ecosystem: npm
  directory: "/js"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tippy.js
    versions:
    - "> 5.1.1, < 6"
  - dependency-name: vue-i18n-extract
    versions:
    - 1.1.11
    - 1.2.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.22
    - 26.0.23
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.9.1
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: buefy
    versions:
    - 0.9.5
    - 0.9.6
    - 0.9.7
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
    - 8.2.0
  - dependency-name: date-fns
    versions:
    - 2.17.0
    - 2.20.1
    - 2.20.2
    - 2.20.3
    - 2.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.9.0
  - dependency-name: vue-i18n
    versions:
    - 8.23.0
    - 8.24.0
    - 8.24.1
    - 8.24.3
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.3
    - 1.1.4
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: mock-apollo-client
    versions:
    - 0.6.0
  - dependency-name: tiptap
    versions:
    - 1.32.1
    - 1.32.2
  - dependency-name: tiptap-extensions
    versions:
    - 1.35.1
    - 1.35.2
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-plugin-pwa"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-plugin-router"
    versions:
    - 4.5.12
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.12
  - dependency-name: leaflet.locatecontrol
    versions:
    - 0.72.2
    - 0.73.0
  - dependency-name: "@types/prosemirror-model"
    versions:
    - 1.12.0
  - dependency-name: "@types/leaflet"
    versions:
    - 1.7.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: vue-apollo
    versions:
    - 3.0.7
  - dependency-name: sass-loader
    versions:
    - 11.0.0
